# Generated by Django 4.2.7 on 2023-12-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_varitation_category_variation_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
