# Generated by Django 4.2.7 on 2023-12-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productvariation_delete_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
    ]
