# Generated by Django 4.2.7 on 2023-12-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
