# Generated by Django 4.2.7 on 2024-01-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
