# Generated by Django 4.2.7 on 2024-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_variation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='variation/products/'),
        ),
    ]
