# Generated by Django 4.2.7 on 2024-01-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_variationimage_product_variationimage_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
