# Generated by Django 4.2.7 on 2024-01-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_variation_image_variationimage'),
        ('carts', '0002_alter_wishlist_product_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variationimage'),
        ),
    ]
