# Generated by Django 4.2.7 on 2024-01-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_variation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation_image',
        ),
    ]
