# Generated by Django 4.2.7 on 2023-12-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_coupon_alter_color_color_alter_color_color_code_and_more'),
        ('carts', '0007_remove_cartitem_variations_cartitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coupon'),
        ),
    ]
