# Generated by Django 4.2.7 on 2023-11-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_active',
            new_name='is_verified',
        ),
    ]
