# Generated by Django 4.2.7 on 2023-11-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_is_active_account_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_verified',
            new_name='is_active',
        ),
    ]
