# Generated by Django 4.2.7 on 2023-12-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_payment_method_remove_payment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cod', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
    ]
