# Generated by Django 4.2.7 on 2023-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Ordered', 'Ordered'), ('Processing', 'Processing'), ('shipped', 'shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('refunded', 'refunded'), ('Return Initiated', 'return_initiated')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=250),
        ),
    ]
