# Generated by Django 4.2.7 on 2023-12-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderproduct_ordered_orderproduct_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
