# Generated by Django 4.2.7 on 2023-12-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderproduct_payment_remove_orderproduct_variations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
    ]
