# Generated by Django 4.2.7 on 2024-01-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
